# Generated by Django 6.0.4 on 2026-04-10 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='last_assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
