# Generated by Django 6.0.4 on 2026-04-10 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_vendor_last_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
