# Generated by Django 6.0.4 on 2026-04-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_vendor_bio_vendor_joined_date_vendor_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=20),
        ),
    ]
