# Generated by Django 6.0.4 on 2026-04-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_order_mpesa_code_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('badge', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('speed', models.CharField(blank=True, max_length=200)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('highlights', models.JSONField(default=list)),
                ('contents', models.JSONField(default=list)),
                ('use_cases', models.JSONField(default=list)),
                ('pricing', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
