# Generated by Django 6.0.4 on 2026-04-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_phase2_referral_courier_performance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvestcalendar',
            options={},
        ),
        migrations.RenameField(
            model_name='harvestcalendar',
            old_name='available_from',
            new_name='date_available',
        ),
        migrations.RenameField(
            model_name='orderbatch',
            old_name='dispatch_to_customer_at',
            new_name='dispatched_to_customers_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='vendor_name',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='harvestcalendar',
            name='available_until',
        ),
        migrations.RemoveField(
            model_name='harvestcalendar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='harvestcalendar',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='harvestcalendar',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carbon_saved_kg',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_applied',
        ),
        migrations.RemoveField(
            model_name='referralcredit',
            name='referred_phone',
        ),
        migrations.RemoveField(
            model_name='referralcredit',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_flagged',
        ),
        migrations.AddField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='marketplace.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='carbon_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='harvestcalendar',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='marketplace.vendor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderbatch',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.courier'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='referralcredit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.CreateModel(
            name='VendorPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('ABSENT', 'Absent'), ('MISS', 'Miss'), ('STRIKE', 'Strike')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='marketplace.vendor')),
            ],
        ),
    ]
