# Generated by Django 6.0.4 on 2026-04-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_harvestcalendar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Mama Fresh', max_length=100)),
                ('brand_phone', models.CharField(default='254792705921', max_length=20)),
                ('mission_statement', models.TextField(blank=True)),
                ('impact_farmers_override', models.IntegerField(blank=True, null=True)),
                ('impact_families_override', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='towncoordinator',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
