# Generated by Django 6.0.4 on 2026-04-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchvendorassignment',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='batchvendorassignment',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OK', 'OK'), ('AMENDED', 'Amended'), ('SHORT', 'Shortage')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='batchvendorassignment',
            name='verified_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderbatch',
            name='hub_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
